In [2]:
import pandas as pd

## Problem-1:
Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [3]:
lst = [10, 20, 30, 40, 50]

df_lst = pd.Series(lst)


print(df_lst.dtype)
for i in df_lst.index :
    print(i, end=" ")
df_lst

int64
0 1 2 3 4

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
tup = (
    ("Akash", 22, "Dhaka"),
    ("Raihan", 21, "Barishal"),
    ("Habib", 18, "Sylhet"),
    ("Ash", 20, "PaletTown")
)

tup_df = pd.DataFrame(tup, columns=["Name", "Age", "City"])
tup_df

     Name  Age       City
0   Akash   22      Dhaka
1  Raihan   21   Barishal
2   Habib   18     Sylhet
3     Ash   20  PaletTown

## Problem-2:
Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [5]:
df = pd.read_csv("student_data.csv")
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [6]:
print(df.columns.size, df.index.size)

print(df.columns.dtype)

df.describe()

9 20
str

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

## Problem-3:
Create a DataFrame using the dictionary below:


data = {

    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    
    'Price': [10, 50, 5, 7],
    
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row.

In [7]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],

    'Price': [10, 50, 5, 7],

    'Quantity': [100, 60, 200, 150]
}

data_df = pd.DataFrame(data)

print(data_df.columns)
data_df.index

Index(['Product', 'Price', 'Quantity'], dtype='str')

RangeIndex(start=0, stop=4, step=1)

In [8]:
# data_df["Product"]
data_df.Product

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: str

In [9]:
data_df.loc[0]

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

## Problem-4:
Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [10]:
print(data_df.loc[0])
print(data_df.iloc[0])

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object
Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [11]:
print(df.loc[:, "FullName"])
print(df.iloc[:, 1:2])

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: str
            FullName
0        Alif Rahman
1      Fatima Akhter
2      Imran Hossain
3   Jannatul Ferdous
4        Kamal Uddin
5        Laila Begum
6     Mahmudul Hasan
7        Nadia Islam
8         Omar Faruq
9       Priya Sharma
10      Rahim Sheikh
11   Sadia Chowdhury
12      Tanvir Ahmed
13        Urmi Akter
14      Wahiduzzaman
15      Ziaur Rahman
16       Afsana Mimi
17       Babul Ahmed
18      Faria Rahman
19        Nasir Khan

In [12]:
print(df.loc[9:11, ["Python Marks", "CompletionStatus"]])
print(df.iloc[9:11, 4:6])

    Python Marks CompletionStatus
9           88.0        Completed
10          91.0      In Progress
11          87.0        Completed
    Python Marks CompletionStatus
9           88.0        Completed
10          91.0      In Progress

## Problem-5: 
Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), 
drop one row by index

In [16]:
lst = [
    ["Raihan", 80, 3.3],
    ["Habib", 84, 3.5],
    ["Akash", 94, 4]
]

df = pd.DataFrame(lst, columns=["Name", "Roll", "CG"])
df

     Name  Roll   CG
0  Raihan    80  3.3
1   Habib    84  3.5
2   Akash    94  4.0

In [17]:
df.drop(0, inplace=True)

df

    Name  Roll   CG
1  Habib    84  3.5
2  Akash    94  4.0

In [20]:
df.drop("CG", axis=1, inplace=True)

df

    Name  Roll
1  Habib    84
2  Akash    94

## Problem-6:
Create a DataFrame of employees with columns "Name", "Department", and 
"Salary". Sort it by "Salary" in ascending order and by "Name" in descending 
order

In [31]:
dirc = {
    "Name": ["Raihan", "Zap", "Habib", "Akash", "Bro"],
    "Department": ["Cse", "EEE", "Math", "English", "Software"],
    "Salary": [1e5, 1e2, 1e4, 1e5, 1e5]
}

df = pd.DataFrame(dirc)

df

     Name Department    Salary
0  Raihan        Cse  100000.0
1     Zap        EEE     100.0
2   Habib       Math   10000.0
3   Akash    English  100000.0
4     Bro   Software  100000.0

In [32]:
df.sort_values(["Salary", "Name"], ascending=[1, 0], inplace=True)

df

     Name Department    Salary
1     Zap        EEE     100.0
2   Habib       Math   10000.0
0  Raihan        Cse  100000.0
4     Bro   Software  100000.0
3   Akash    English  100000.0

## Problem-7:
Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print 
students with Score > 60 and those with Score < 40

In [36]:
tup = (
    ("Raihan", 89),
    ("Habib", 90),
    ("Bro", 33),
    ("Akash", 93),
    ("Ash", 23),
    ("Niloy", 93),
    ("Sadman", 37),
    ("Tony", 23)
)

df = pd.DataFrame(tup, columns=["Name", "Score"])

df

     Name  Score
0  Raihan     89
1   Habib     90
2     Bro     33
3   Akash     93
4     Ash     23
5   Niloy     93
6  Sadman     37
7    Tony     23

In [37]:
score_above_60 = df.loc[df["Score"] > 60]

score_above_60

     Name  Score
0  Raihan     89
1   Habib     90
3   Akash     93
5   Niloy     93

In [38]:
score_down_40 = df.loc[df["Score"] < 40]

score_down_40

     Name  Score
2     Bro     33
4     Ash     23
6  Sadman     37
7    Tony     23